In [39]:
# DATAFRAMES INITIALISATION

import os
os.chdir('C:\\Users\\asus\\OneDrive\\Documenti\\University Docs\\MSc Computing\\Final Project\\RainbowFood(JN)\\Rainbow-Food-Collaborative-Filtering-')

import pandas as pd

# recipe file
col_list_rec = ['Link', 'Title', 'Total Time', 'Servings', 'Ingredients', 'Instructions']
df_rec = pd.read_csv("Recipes.csv", usecols = col_list_rec)

# ratings
col_list_rat = ["userId", "recipeId", "rating"]
df_ratings = pd.read_csv("Ratings_smaller.csv", usecols = col_list_rat)
df_ratings_test = pd.read_csv("Ratings_test.csv", usecols = col_list_rat)

In [40]:
print("Tuple numbers of rows and column: ", df_ratings.shape)
n_users = df_ratings.userId.unique().shape[0]
n_recipes = df_ratings.recipeId.unique().shape[0]
print("Number of users : ", n_users,"\t", "Number of recipes: ", n_recipes)

import numpy as np
unique_users = df_ratings.userId.unique().tolist()
unique_recipes = df_ratings.recipeId.unique().tolist()
ratings = np.zeros((n_users, n_items))
for line in df_ratings.itertuples():
    userId = line[1] # ie. 279
    recipeId = line[2] 
    
    unique_userId_index = unique_users.index(userId)
    unique_recipeId_index = unique_recipes.index(recipeId)
    ratings[unique_userId_index, unique_recipeId_index] = line[3]
ratings

Tuple numbers of rows and column:  (2876, 3)
Number of users :  557 	 Number of recipes:  24


array([[2.5, 3. , 3. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 4. , 4. , 3. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 4. , 0. , ..., 5. , 5. , 0. ]])

In [17]:
sparsity = float(len(ratings.nonzero()[0]))
sparsity /= (ratings.shape[0] * ratings.shape[1])
sparsity *= 100
print('Sparsity: {:4.2f}%'.format(sparsity))

Sparsity: 19.48%


In [38]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(ratings, metric='cosine')
recipe_similarity = pairwise_distances(ratings.T, metric='cosine')
print("This is the user_similarity\n", user_similarity)
print("\n")
print("This is the recipe_similarity\n", recipe_similarity)

This is the user_similarity
 [[0.         0.81936303 0.50378469 ... 0.74371609 0.66781808 0.8773337 ]
 [0.81936303 0.         0.83785357 ... 0.67182451 1.         0.52401186]
 [0.50378469 0.83785357 0.         ... 1.         0.47585758 1.        ]
 ...
 [0.74371609 0.67182451 1.         ... 0.         1.         0.71509856]
 [0.66781808 1.         0.47585758 ... 1.         0.         1.        ]
 [0.8773337  0.52401186 1.         ... 0.71509856 1.         0.        ]]


This is the recipe_similarity
 [[0.         0.89472526 0.75261348 0.79955182 0.91642655 0.84789831
  0.77437    0.80008322 0.92920072 0.7662686  0.73619828 0.68582929
  0.8699018  0.89543071 0.87261934 0.83188016 0.81653018 0.87491942
  0.8487278  0.81613284 0.75297138 0.73819146 0.75009123 0.80694883]
 [0.89472526 0.         0.54721654 0.64122067 0.76642342 0.68577247
  0.58679027 0.69189065 0.76861455 0.70653501 0.66518836 0.59444823
  0.67932235 0.70368248 0.67452966 0.75283453 0.62239302 0.62216483
  0.69225927 0.61